version: '3.9'

networks:
  baha2365-backend-circlesave-net:
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: circlesave-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - baha2365-backend-circlesave-net

  backend:
    build: .
    container_name: circlesave-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/CircleSave
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 3000
      JWT_ACCESS_SECRET: super_secret_access_key_very_long_123456
      JWT_REFRESH_SECRET: super_secret_refresh_key_very_long_654321
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      API_VERSION: v1
      CORS_ORIGINS: http://localhost:3000,http://localhost,https://baha2365-backend-circlesave-frontend.kazi.rocks
      FRONTEND_URL: https://baha2365-backend-circlesave-frontend.kazi.rocks
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node src/server.js"
    networks:
      - baha2365-backend-circlesave-net

  postgres:
    image: postgres:16
    container_name: circlesave-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: CircleSave
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CircleSave"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - baha2365-backend-circlesave-net

  redis:
    image: redis:7
    container_name: circlesave-redis
    restart: always
    networks:
      - baha2365-backend-circlesave-net

volumes:
  pgdata: